services:
  database:
    container_name: tiktok-postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres
      - POSTGRES_PASSWORD=postgres
   